### ISSUE TITLE
Error when running benchmark

### ISSUE THREAD

**Issue by Kyridiculous2** [facebookresearch/habitat-api#203]
After running python examples/benchmark.py
 I got 

2019-09-16 12:23:19,177 initializing sim Sim-v0
Traceback (most recent call last):
  File "examples/benchmark.py", line 38, in <module>
    main()
  File "examples/benchmark.py", line 30, in main
    benchmark = habitat.Benchmark(args.task_config)
  File "/data_1/codes/habitat-api/habitat/core/benchmark.py", line 30, in __init__
    self._env = Env(config=config_env)
  File "/data_1/codes/habitat-api/habitat/core/env.py", line 96, in __init__
    id_sim=self._config.SIMULATOR.TYPE, config=self._config.SIMULATOR
  File "/data_1/codes/habitat-api/habitat/sims/registration.py", line 19, in make_sim
    return _sim(**kwargs)
  File "/data_1/codes/habitat-api/habitat/sims/habitat_simulator/habitat_simulator.py", line 166, in __init__
    self.sim_config = self.create_sim_config(self._sensor_suite)
  File "/data_1/codes/habitat-api/habitat/sims/habitat_simulator/habitat_simulator.py", line 199, in create_sim_config
    self.config.HABITAT_SIM_V0.GPU_GPU
AttributeError: 'habitat_sim._ext.habitat_sim_bindings.SensorSpec' object has no attribute 'gpu2gpu_transfer'

**Comment by Kyridiculous2** [comment]
fixed after upgrade habitat-sim
