### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'configs/tasks/pointnav.yaml'

### ISSUE THREAD

**Issue by chale96** [facebookresearch/habitat-api#317]
## ❓ Questions and Help
Sorry for being a pain but I am keeping getting errors while trying to use habitat-api..

I am trying to run `python examples/example.py` (from installation: https://github.com/facebookresearch/habitat-api#installation) and  I am getting this error:

Traceback (most recent call last):
  File "habitat-api/examples/example.py", line 25, in <module>
    example()
  File "habitat-api/examples/example.py", line 11, in example
    env = habitat.Env(config=habitat.get_config("configs/tasks/pointnav.yaml"))
  File "/Users/alessandrocandeloro/Documents/University/in3007_ind_proj/implementation/habitat-api/habitat/config/default.py", line 350, in get_config
    config.merge_from_file(config_path)
  File "/Users/alessandrocandeloro/anaconda3/envs/habitat/lib/python3.6/site-packages/yacs/config.py", line 211, in merge_from_file
    with open(cfg_filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/tasks/pointnav.yaml'

**Comment by mathfac** [comment]
Double check that your current directory is ‘habitat-api’. All runnables
should be run from ‘habitat-Apis’ directory.

**Comment by chale96** [comment]
Thank you
