### ISSUE TITLE
import habitat_sim ModuleNotFoundError: No module named 'habitat_sim'

### ISSUE THREAD

**Issue by chale96** [facebookresearch/habitat-api#340]
## ❓ Questions and Help
I am running an action example that last week use to run. Now when I try to run it again it gives me:
```
(habitat) alessandrocandeloro@Alessandros-MacBook-Pro implementation % python randomActions.py
Traceback (most recent call last):
  File "randomActions.py", line 3, in <module>
    from habitat.sims.habitat_simulator.actions import HabitatSimActions
  File "/Users/alessandrocandeloro/Documents/University/in3007_ind_proj/implementation/habitat-api/habitat/sims/habitat_simulator/actions.py", line 12, in <module>
    import habitat_sim
ModuleNotFoundError: No module named 'habitat_sim'
```

### What I tried:
- `export PYTHONPATH=$PYTHONPATH:/path/to/habitat-sim` 

- `unset PYTHONPATH`

**Comment by chale96** [comment]
I unset PYTHONPATH but now I have this new error:
```
alessandrocandeloro@Alessandros-MacBook-Pro implementation % python randomActions.py
Traceback (most recent call last):
  File "randomActions.py", line 3, in <module>
    from habitat.sims.habitat_simulator.actions import HabitatSimActions
  File "/Users/alessandrocandeloro/Documents/University/in3007_ind_proj/implementation/habitat-api/habitat/sims/habitat_simulator/actions.py", line 12, in <module>
    import habitat_sim
  File "/Users/alessandrocandeloro/Documents/University/in3007_ind_proj/implementation/habitat-sim/habitat_sim/__init__.py", line 14, in <module>
    from habitat_sim.nav import *
  File "/Users/alessandrocandeloro/Documents/University/in3007_ind_proj/implementation/habitat-sim/habitat_sim/nav/__init__.py", line 1, in <module>
    from habitat_sim._ext.habitat_sim_bindings import (
ImportError: ModuleNotFoundError: No module named 'magnum'
```

**Comment by chale96** [comment]
### Fixed with:

`git pull origin master`
`conda activate [env_name]`
`pip install requirements.txt`
`python setup.py install`
