### ISSUE TITLE
KeyError: 'pointgoal_with_gps_compass' with mp3d dataset

### ISSUE THREAD

**Issue by chale96** [facebookresearch/habitat-api#348]
## ❓ Questions and Help

I am trying to use the mp3d dataset but I am getting this error: `KeyError: 'pointgoal_with_gps_compass'` when running the code I wrote for the example dataset.

```
Traceback (most recent call last):
  File "randomActions.py", line 86, in <module>
    example()
  File "randomActions.py", line 35, in example
    observations["pointgoal_with_gps_compass"][0], observations["pointgoal_with_gps_compass"][1]))
KeyError: 'pointgoal_with_gps_compass'
```

**Comment by chale96** [comment]
I was using the wrong config
